repos:
- repo: local
  hooks:
    - id: alejandra
      name: alejandra
      entry: alejandra
      language: system
      types: [nix]

    - id: deadnix
      name: deadnix
      entry: deadnix
      language: system
      types: [nix]

    - id: statix
      name: statix
      entry: statix check
      language: system
      pass_filenames: false
      always_run: true

    - id: ruff
      name: ruff
      entry: ruff check --fix
      language: system
      types: [python]

    - id: ruff-format
      name: ruff-format
      entry: ruff format
      language: system
      types: [python]
